# Generated by Django 3.0.1 on 2019-12-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediate_element',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
