# Generated by Django 3.0.1 on 2020-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_customer_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('YEAR', models.IntegerField()),
                ('MONTH', models.IntegerField()),
                ('DAY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_payment_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('YEAR', models.IntegerField()),
                ('MONTH', models.IntegerField()),
                ('DAY', models.IntegerField()),
                ('item', models.IntegerField()),
                ('num', models.FloatField()),
            ],
        ),
    ]
