# Generated by Django 3.0.1 on 2019-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20191228_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpsStr', models.CharField(max_length=20)),
            ],
        ),
    ]
